### ISSUE TITLE
java.lang.IllegalArgumentException: Permission can not be null for sid:authenticated

### ISSUE THREAD

**Issue by sravanikollipara** [aws-samples/serverless-jenkins-on-aws-fargate#16] opened 2021-09-21 16:47 UTC
Post provisioning the terraform and I see below errors on Jenkins console.

I have used same configuration as it is for plugins and jenkins.yaml.tpl

<img width="1511" alt="Screen Shot 2021-09-21 at 11 47 05 AM" src="https://user-images.githubusercontent.com/57202043/134212972-6ccee091-0563-4baf-9360-a7a592dfa03b.png">

**Comment by arawak-consulting** [comment] 2021-09-27 20:17
I have the same issue ; how to resolve ?

**Comment by apogorielov** [comment] 2021-11-10 16:37
Unfortunately I was not able to reproduce this issue in #21 therefor closing this. Please feel free to re-open with details step to reproduce this issue.

**Closed by apogorielov** 2021-11-10 16:37 UTC
